# Generated by Django 3.1.7 on 2021-03-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('info', models.CharField(max_length=64, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Базовая модель',
                'verbose_name_plural': 'Базовые модели',
            },
        ),
    ]
