# Generated by Django 3.1.7 on 2021-03-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localetest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmodel',
            name='name_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='name_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
