# Generated by Django 3.1.7 on 2021-03-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localetest', '0002_auto_20210301_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=32, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=32, null=True, verbose_name='Название')),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localetest.basicmodel')),
            ],
        ),
    ]
